Vagrant.configure(2) do |config|

# ... your existing config

  # Custom configuration for docker
  config.vm.provider "docker" do |docker, override|
    # docker doesnt use boxes
    override.vm.box = nil

    # this is where your Dockerfile lives
    docker.build_dir = "."

    # Make sure it sets up ssh with the Dockerfile
    # Vagrant is pretty dependent on ssh
    override.ssh.insert_key = true
    docker.has_ssh = true
    docker.privileged = true
    # Setting docker args to run. Gives us a lot of power!
    docker.create_args = ["--hostname=cs4254-transport", "--cap-add", "NET_ADMIN", "-m", "1g", "--cpus=2"]
    # Configure Docker to allow access to more resources
    
  end
  config.vm.synced_folder "..", "/cs4254"
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y net-tools build-essential
    ln -s /cs4254 /home/vagrant/cs4254
    /cs4254/infra/init.bash
  SHELL

# ...

end
